=== Alexander-Roman/Greenhouse/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.epam.com/greenhouse"
	xmlns:tns="http://www.epam.com/greenhouse"
	elementFormDefault="qualified">

	<xs:complexType name="flowersElement">
		<xs:sequence>
			<xs:element ref="tns:flower" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="flowerElement">	
		<xs:sequence>
			<xs:element name="name" type="tns:flowerName"/>
			<xs:element name="price" type="tns:flowerPrice" default="0.0"/>
		</xs:sequence>
		<xs:attribute name="id" type="tns:flowerId" use="required"/> 
	</xs:complexType>

	<xs:simpleType name="flowerId">
		<xs:restriction base="xs:ID">
			<xs:pattern value="f\d{4}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="flowerName">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z\s]+"/>
			<xs:whiteSpace value="replace"/>
			<xs:minLength value="3"/>
			<xs:maxLength value="128"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="flowerPrice">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="cutFlowerElement">	
		<xs:complexContent>
			<xs:extension base="tns:flowerElement">
				<xs:sequence>
					<xs:element name="flowerType" type="tns:flowerTypeElement"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="flowerTypeElement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SINGLE"/>
			<xs:enumeration value="BUSH"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="pottedFlowerElement">	
		<xs:complexContent>
			<xs:extension base="tns:flowerElement">
				<xs:sequence>
					<xs:element name="bloomAble" type="tns:bloomAbleElement"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="bloomAbleElement">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>

	<xs:element name="flowers" type="tns:flowersElement"/>
	<xs:element name="flower" type="tns:flowerElement" abstract="true"/>
	<xs:element name="cutFlower" type="tns:cutFlowerElement" substitutionGroup="tns:flower"/>
	<xs:element name="pottedFlower" type="tns:pottedFlowerElement" substitutionGroup="tns:flower"/>

</xs:schema>

=== Alexander-Roman/Greenhouse/data/flowers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<flowers xmlns="http://www.epam.com/greenhouse"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="flowers.xsd">
	<cutFlower id="f1000">
		<name>Hybrid Tea Rose</name>
		<price>5.50</price>
		<flowerType>SINGLE</flowerType>
	</cutFlower>

	<cutFlower id="f1001">
		<name>Climbing Rose</name>
		<price>4.85</price>
		<flowerType>BUSH</flowerType>
	</cutFlower>

	<pottedFlower id="f1002">
		<name>Floribunda</name>
		<price>11.65</price>
		<bloomAble>0</bloomAble>
	</pottedFlower>

	<pottedFlower id="f1003">
		<name>Grandiflora</name>
		<price>16.00</price>
		<bloomAble>1</bloomAble>
	</pottedFlower>
</flowers>
